devices:

- device_id: 1
  device_type: KUB-1063
  slave_id: 1
  name: 'KUB-1063 #1'
  description: Автоскан EDGE
  enabled: true
  location: null
  poll_interval: 1.0

- device_id: 2
  device_type: KUB-1063
  slave_id: 2
  name: 'KUB-1063 #2'
  description: Автоскан EDGE
  enabled: true
  location: null
